src/Hris.WebApplication/Models/ErrorViewModel.cs
using System;

namespace Hris.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Hris.WebApplication/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Hris.WebApplication.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Index()
        {
            return View();
        }
      

        // POST: Auth/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
      
    }
}

src/Hris.WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Hris.WebApplication.Models;

namespace Hris.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
      

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Hris.WebApplication/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hris.WebApplication.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Hris.WebApplication/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hris.WebApplication.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {                
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Hris.WebApplication/ViewComponents/MenuViewComponent.cs
using Hris.Infrastructure.Database.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hris.WebApplication.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly List<MenuItem> _menus;

        public MenuViewComponent()
        {

            _menus = new List<MenuItem>
            {
                new MenuItem { Id = Guid.NewGuid(), Position = 1, Title = "Dashboard", Url = "~/", Icon = "md md-dashboard" },
                new MenuItem { Id = Guid.NewGuid(), Position = 2, Title = "Master", Url = "~/Master", Icon = "md md-group" },
                new MenuItem { Id = Guid.NewGuid(), Position = 3, Title = "Administration", Url = "~/Adminstration", Icon = "md md-account-child" },                
                new MenuItem { Id = Guid.NewGuid(), Position = 4, Title = "Attendance", Url = "~/Attendance", Icon = "md md-av-timer" },
                new MenuItem { Id = Guid.NewGuid(), Position = 5, Title = "Leaving", Url = "~/Leaving", Icon = "md md-exit-to-app" },
                new MenuItem { Id = Guid.NewGuid(), Position = 6, Title = "Medical", Url = "~/Medical", Icon = "md md-local-hospital" },
                new MenuItem { Id = Guid.NewGuid(), Position = 7, Title = "Organization", Url = "~/Organization", Icon = "md md-group" },                    
                new MenuItem { Id = Guid.NewGuid(), Position = 7, Title = "Payroll", Url = "~/Payroll", Icon = "md md-attach-money" },
                new MenuItem { Id = Guid.NewGuid(), Position = 9, Title = "Appraisals", Url = "~/PerformanceAppraisals", Icon = "md md-trending-up" },
                new MenuItem { Id = Guid.NewGuid(), Position = 10, Title = "Recruitment", Url = "~/Recruitment", Icon = "md md-group-add" },
                new MenuItem { Id = Guid.NewGuid(), Position = 11, Title = "Training", Url = "~/Training", Icon = "md md-school" },
                new MenuItem { Id = Guid.NewGuid(), Position = 12, Title = "Travelling", Url = "~/Travelling", Icon = "md md-public" }
            };

            _menus.Add(new MenuItem { Id = Guid.NewGuid(), Position = 1, Title = "Branch", Url = "~/Organization/Master", Icon = "md md-account-child", Parent = _menus.Where(x => x.Title.Contains("Master")).SingleOrDefault().Id });
            _menus.Add(new MenuItem { Id = Guid.NewGuid(), Position = 2, Title = "Division", Url = "~/Organization/Master/Division", Icon = "md md-account-child", Parent = _menus.Where(x => x.Title.Contains("Master")).SingleOrDefault().Id });




        }

        public async Task<IViewComponentResult> InvokeAsync()
        {           
            return await Task.FromResult((IViewComponentResult)View("Default", _menus));
        }
    }
}

src/Hris.WebApplication/ViewComponents/RightSidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hris.WebApplication.ViewComponents
{
    public class RightSidebarViewComponent : ViewComponent
    {                
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Hris.WebApplication/ViewComponents/ThemeScriptsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hris.WebApplication.ViewComponents
{
    public class ThemeScriptsViewComponent : ViewComponent
    {                
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Hris.WebApplication/ViewComponents/TopBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hris.WebApplication.ViewComponents
{
    public class TopBarViewComponent : ViewComponent
    {                
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Hris.WebApplication/Views/Home/Index.cshtml
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-header-box">
            <ol class="breadcrumb pull-right mb-0">
                <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                <li class="breadcrumb-item active">Dashboard 3</li>
            </ol>
            <h4 class="page-title">Dashboard 3</h4>
            <div class="clearfix"></div>
        </div>

    </div>
</div>


<div class="row">
    <div class="col-lg-12 col-xl-4">
        <div class="card-box">
            <div class="bar-widget">
                <div class="table-box">
                    <div class="table-detail">
                        <div class="iconbox bg-info">
                            <i class="icon-layers"></i>
                        </div>
                    </div>

                    <div class="table-detail">
                        <h4 class="m-t-0 m-b-5"><b>12560</b></h4>
                        <p class="text-muted m-b-0 m-t-0">Total Revenue</p>
                    </div>
                    <div class="table-detail text-right">
                        <span data-plugin="peity-bar" data-colors="#34d3eb,#ebeff2" data-width="120" data-height="45">5,3,9,6,5,9,7,3,5,2,9,7,2,1</span>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-xl-4">
        <div class="card-box">
            <div class="bar-widget">
                <div class="table-box">
                    <div class="table-detail">
                        <div class="iconbox bg-custom">
                            <i class="icon-layers"></i>
                        </div>
                    </div>

                    <div class="table-detail">
                        <h4 class="m-t-0 m-b-5"><b>356</b></h4>
                        <p class="text-muted m-b-0 m-t-0">Ave. weekly Sales</p>
                    </div>
                    <div class="table-detail text-right">
                        <span data-plugin="peity-pie" data-colors="#5fbeaa,#ebeff2" data-width="50" data-height="45">1/5</span>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-xl-4">
        <div class="card-box">
            <div class="bar-widget">
                <div class="table-box">
                    <div class="table-detail">
                        <div class="iconbox bg-danger">
                            <i class="icon-layers"></i>
                        </div>
                    </div>

                    <div class="table-detail">
                        <h4 class="m-t-0 m-b-5"><b>96562</b></h4>
                        <p class="text-muted m-b-0 m-t-0">Visiters</p>
                    </div>
                    <div class="table-detail text-right">
                        <span data-plugin="peity-donut" data-colors="#f05050,#ebeff2" data-width="50" data-height="45">1/5</span>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">

    <div class="col-lg-12 col-xl-4">
        <div class="card-box">
            <h4 class="text-dark header-title m-t-0 m-b-30">Daily Sales</h4>

            <div class="widget-chart text-center">
                <div id="sparkline3"></div>
                <ul class="list-inline m-t-15">
                    <li>
                        <h5 class="text-muted m-t-20">Target</h5>
                        <h4 class="m-b-0">$1000</h4>
                    </li>
                    <li>
                        <h5 class="text-muted m-t-20">Last week</h5>
                        <h4 class="m-b-0">$523</h4>
                    </li>
                    <li>
                        <h5 class="text-muted m-t-20">Last Month</h5>
                        <h4 class="m-b-0">$965</h4>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <div class="col-lg-12 col-xl-4">
        <div class="card-box">
            <h4 class="text-dark  header-title m-t-0 m-b-30">Monthly Sales</h4>

            <div class="widget-chart text-center">
                <div id="sparkline1"></div>
                <ul class="list-inline m-t-15">
                    <li>
                        <h5 class="text-muted m-t-20">Target</h5>
                        <h4 class="m-b-0">$1000</h4>
                    </li>
                    <li>
                        <h5 class="text-muted m-t-20">Last week</h5>
                        <h4 class="m-b-0">$523</h4>
                    </li>
                    <li>
                        <h5 class="text-muted m-t-20">Last Month</h5>
                        <h4 class="m-b-0">$965</h4>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <div class="col-lg-12 col-xl-4">
        <div class="card-box">
            <h4 class="text-dark  header-title m-t-0 m-b-30">Weekly Sales</h4>

            <div class="widget-chart text-center">
                <div id="sparkline2"></div>
                <ul class="list-inline m-t-15">
                    <li>
                        <h5 class="text-muted m-t-20">Target</h5>
                        <h4 class="m-b-0">$1000</h4>
                    </li>
                    <li>
                        <h5 class="text-muted m-t-20">Last week</h5>
                        <h4 class="m-b-0">$523</h4>
                    </li>
                    <li>
                        <h5 class="text-muted m-t-20">Last Month</h5>
                        <h4 class="m-b-0">$965</h4>
                    </li>
                </ul>
            </div>
        </div>

    </div>

</div>

<!-- end row -->

<div class="row">

    <div class="col-12">

        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark text-uppercase">
                    Projects
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet2"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet2" class="panel-collapse collapse show">
                <div class="portlet-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Project Name</th>
                                    <th>Start Date</th>
                                    <th>Due Date</th>
                                    <th>Status</th>
                                    <th>Assign</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Ubold Admin v1</td>
                                    <td>01/01/2015</td>
                                    <td>26/04/2015</td>
                                    <td><span class="label label-info">Released</span></td>
                                    <td>Coderthemes</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Ubold Frontend v1</td>
                                    <td>01/01/2015</td>
                                    <td>26/04/2015</td>
                                    <td><span class="label label-success">Released</span></td>
                                    <td>Coderthemes</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Ubold Admin v1.1</td>
                                    <td>01/05/2015</td>
                                    <td>10/05/2015</td>
                                    <td><span class="label label-pink">Pending</span></td>
                                    <td>Coderthemes</td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>Ubold Frontend v1.1</td>
                                    <td>01/01/2015</td>
                                    <td>31/05/2015</td>
                                    <td><span class="label label-purple">Work in Progress</span></td>
                                    <td>Coderthemes</td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>Ubold Admin v1.3</td>
                                    <td>01/01/2015</td>
                                    <td>31/05/2015</td>
                                    <td><span class="label label-warning">Coming soon</span></td>
                                    <td>Coderthemes</td>
                                </tr>

                                <tr>
                                    <td>6</td>
                                    <td>Ubold Admin v1.3</td>
                                    <td>01/01/2015</td>
                                    <td>31/05/2015</td>
                                    <td><span class="label label-primary">Coming soon</span></td>
                                    <td>Coderthemes</td>
                                </tr>

                                <tr>
                                    <td>7</td>
                                    <td>Ubold Admin v1.3</td>
                                    <td>01/01/2015</td>
                                    <td>31/05/2015</td>
                                    <td><span class="label label-info">Cool</span></td>
                                    <td>Coderthemes</td>
                                </tr>

                                <tr>
                                    <td>8</td>
                                    <td>Ubold Admin v1.3</td>
                                    <td>01/01/2015</td>
                                    <td>31/05/2015</td>
                                    <td><span class="label label-warning">Coming soon</span></td>
                                    <td>Coderthemes</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- end col -->

</div>

<!-- end row -->

src/Hris.WebApplication/Views/Shared/Components/Footer/Default.cshtml
<footer class="footer text-right">
    &copy; 2016 - 2017. All rights reserved.
</footer>

src/Hris.WebApplication/Views/Shared/Components/Header/Default.cshtml
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
<meta name="author" content="Coderthemes">

<link rel="shortcut icon" href="~/theme2-assets/images/favicon.ico">

<title>HRIS</title>

<!--Morris Chart CSS -->
<link rel="stylesheet" href="~/theme2-assets/plugins/morris/morris.css">
<link href="~/theme2-assets/plugins/bootstrap-sweetalert/sweet-alert.css" rel="stylesheet" type="text/css">

<link href="~/theme2-assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="~/theme2-assets/css/icons.css" rel="stylesheet" type="text/css" />
<link href="~/theme2-assets/css/style.css" rel="stylesheet" type="text/css" />

<script src="~/theme2-assets/js/modernizr.min.js"></script>   

src/Hris.WebApplication/Views/Shared/Components/Menu/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<Hris.Infrastructure.Database.Models.MenuItem>

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">Navigation</li>
                @foreach (var menuItem in Model.Where(x => !x.Parent.HasValue).OrderBy(x => x.Position))
                {
                    var url = menuItem.Url;
                    var target = "_self";

                    if (url.StartsWith("~"))
                        url = Url.Content(url);

                    if (menuItem.OpenInNewWindow)
                        target = "_blank";

                    var hasParent = Model.Where(x => x.Parent == menuItem.Id);

                    if (hasParent.Any())
                    {
                        <li class="has_sub">
                            <a href="javascript:void(0);" class="waves-effect"><i class="@menuItem.Icon"></i> <span> @menuItem.Title </span> <span class="menu-arrow"></span></a>
                            <ul class="list-unstyled">
                                @foreach (var subMenu in hasParent.OrderBy(x => x.Position))
                                {
                                    if (subMenu.Url.StartsWith("~"))
                                        url = Url.Content(url);

                                    if (subMenu.OpenInNewWindow)
                                        target = "_blank";

                                    <li><a href="@url" target="@target">@subMenu.Title</a></li>
                                }

                            </ul>
                        </li>
                    }
                    else
                    {

                        <li>
                            <a href="@url" target="@target" class="waves-effect"><i class="@menuItem.Icon"></i> <span> @menuItem.Title </span></a>
                        </li>
                    }
                }
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>


<!-- Left Sidebar End -->

src/Hris.WebApplication/Views/Shared/Components/RightSidebar/Default.cshtml
<div class="side-bar right-bar nicescroll">
    <h4 class="text-center">Chat</h4>
    <div class="contact-list nicescroll">
        <ul class="list-group contacts-list">
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-1.jpg" alt="">
                    </div>
                    <span class="name">Chadengle</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-2.jpg" alt="">
                    </div>
                    <span class="name">Tomaslau</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-3.jpg" alt="">
                    </div>
                    <span class="name">Stillnotdavid</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-4.jpg" alt="">
                    </div>
                    <span class="name">Kurafire</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-5.jpg" alt="">
                    </div>
                    <span class="name">Shahedk</span>
                    <i class="fa fa-circle away"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-6.jpg" alt="">
                    </div>
                    <span class="name">Adhamdannaway</span>
                    <i class="fa fa-circle away"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-7.jpg" alt="">
                    </div>
                    <span class="name">Ok</span>
                    <i class="fa fa-circle away"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-8.jpg" alt="">
                    </div>
                    <span class="name">Arashasghari</span>
                    <i class="fa fa-circle offline"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-9.jpg" alt="">
                    </div>
                    <span class="name">Joshaustin</span>
                    <i class="fa fa-circle offline"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-10.jpg" alt="">
                    </div>
                    <span class="name">Sortino</span>
                    <i class="fa fa-circle offline"></i>
                </a>
                <span class="clearfix"></span>
            </li>
        </ul>
    </div>
</div>

src/Hris.WebApplication/Views/Shared/Components/ThemeScripts/Default.cshtml
<script>
        var resizefunc = [];
</script>

<!-- jQuery  -->
<script src="~/theme2-assets/js/jquery.min.js"></script>
<script src="~/theme2-assets/js/tether.min.js"></script><!-- Tether for Bootstrap -->
<script src="~/theme2-assets/js/bootstrap.min.js"></script>
<script src="~/theme2-assets/js/detect.js"></script>
<script src="~/theme2-assets/js/fastclick.js"></script>
<script src="~/theme2-assets/js/jquery.slimscroll.js"></script>
<script src="~/theme2-assets/js/jquery.blockUI.js"></script>
<script src="~/theme2-assets/js/waves.js"></script>
<script src="~/theme2-assets/js/wow.min.js"></script>
<script src="~/theme2-assets/js/jquery.nicescroll.js"></script>
<script src="~/theme2-assets/js/jquery.scrollTo.min.js"></script>

<!-- jQuery  -->
<script src="~/theme2-assets/plugins/moment/moment.js"></script>


<script src="~/theme2-assets/plugins/morris/morris.min.js"></script>
<script src="~/theme2-assets/plugins/raphael/raphael-min.js"></script>

<script src="~/theme2-assets/plugins/bootstrap-sweetalert/sweet-alert.min.js"></script>

<!-- Todojs  -->
<script src="~/theme2-assets/pages/jquery.todo.js"></script>

<!-- chatjs  -->
<script src="~/theme2-assets/pages/jquery.chat.js"></script>

<script src="~/theme2-assets/plugins/peity/jquery.peity.min.js"></script>

<script src="~/theme2-assets/js/jquery.core.js"></script>
<script src="~/theme2-assets/js/jquery.app.js"></script>

<script src="~/theme2-assets/pages/jquery.dashboard_2.js"></script>

src/Hris.WebApplication/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>

<head>
    @(await Component.InvokeAsync("Header"))
    @RenderSection("Styles", required: false)
</head>

<body class="fixed-left">
    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner">
                <div class="spinner-wrapper">
                    <div class="rotator">
                        <div class="inner-spin"></div>
                        <div class="inner-spin"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Begin page -->
    <div id="wrapper">
        <!-- Top Bar Start -->
        @(await Component.InvokeAsync("TopBar"))
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
        @(await Component.InvokeAsync("Menu"))
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container">
                    @RenderBody()
                </div> <!-- container -->
            </div> <!-- content -->
        </div>
        <!-- end right Content here -->

        @(await Component.InvokeAsync("Footer"))
        @(await Component.InvokeAsync("RightSidebar"))
    </div>
    <!-- END wrapper -->
    @(await Component.InvokeAsync("ThemeScripts"))      
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Hris.WebApplication/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html>
@(await Component.InvokeAsync("Header"))
<body>

    <div class="account-pages"></div>
    <div class="clearfix"></div>

    <div class="wrapper-page">
        @RenderBody()
    </div>
    @(await Component.InvokeAsync("ThemeScripts"))
    @RenderSection("Scripts", required: false)
</body>
</html>